* Themes.
- How and why are we researcing.
- How to do research.
- Where and what are the resources.
- Librarians are not scary.
- Avoiding overwhelm with research, especially with the internet.
* Why are you doing research.
- Your teacher asks you to present work.
- Mentors ask you who you are thinking about during a studio visit.
- Youre feeling stumped in your studio.
- Youre growing your artist family tree.
- Youre looking for insperation.
- To learn more about art history/place your art in art history.
- Looking for artist who are similar to you.
* The Process.
1. Seek resources. Where are you researching?
2. Take notes! Engage with what you found.
* Where do you look at art.
** Asking the class.
- Books are popular.
- Galleries are good.
- Google, but overwelming.
- Looking up your favorite artists favorite artists. 
** Libraries.
-Great resource, like to be asked questions. Most have a "chat with us" feature. Especially art librarians. "What are some contemporary artists who use brush strokes like van gou."
- Most academic libraries will accept anyone, even if your not a student.
- You're not bothering a librarian. Its they job. This is an established phenominon. Based in a fear of asking for help.
- Librarians can give you resources from the library, or point you to resources in your own university.
- The Librarian has special acces to databases and things.
** Art Magazine.
Most of these are abaile through the rutgers art library.
- Art in america
- Artform. See also bookform. 
- Arts Review
- Artsy
- Bomb
- The Brooklyn Rail. Theyre art book reviews are especially good.
- Cultured
- E-flux
- Frieze
- Hyperallergic
- Triple Canopy.
- Two coats of paint.
Find one that fits the way your brain works
When you read art magazines often, you gain a familiarity with the scene, what galleryies are showing, who keeps showing up, what are people talking about, what themes artists are addressing.
Art Mags have columnsa about art.
Search magazines for keywords!
Also look for catalogs, and reviews and art books.
** Websites.
- [Art21.org]
- Gallery Rosters: like a music lable. Go to a gallery you like and click on "artists" or "roster"
- Youtube channels. See slide show. Art in Color. the Lousisian Channel.
** Art Podcasts.
- Art and Obselescence.
- Dialogues: THe David Zwirner Podcast.
- I like your work.
** Others.
- Word of mouth.
- School.
- Seesaw app.
* What Makes good research?
- Search in many places. Google AND QuickSearch AND Libraries.
** What makes a good keyword.
Idenfity broad "themes."
You want to find artists that relate to the theme, not the topic. "tree" not "forest". Searching tree doesnt get you climate change or enviornment or arborism, and a lot of stick art.
** Example
google search: Turtle sculpture: a lot of turtle sculptures.
Rutgers QuickSearch: keyword turtle, subject: sculpture.
** Skimming.
Skimming can take a lot of time and energy. Find what you like and do more of that.
Don't be submissive to your sources. The source is not the god-expert of the research.
** How do you know where to stop?
Research is an infinte well that never ends.
Doing research, especially archive research, making art can be difficult. Something about how brains work. When you feel this, it might be time.
Check in with yourself, mindfulness.
** Retaining information.
The pressure to preform knowlage, to be the person who names drops, is real.
Memory is hard too.
Managing anxiety is important.
Have a system to organize / referance knowlage.
Review before going to an artists talk or studio visit.
If you can talk for something about 90s, you can be considered an "expert"
* Rutgers resources.
There exists a spreadsheet of artists sorted by theme maintained by MGSA staff.
Also an art writing database associated with the painting department. 
** Art library.
Megan Lotts is the library. Very friendly and outgoing. They like people!
Only open 9am-5pm :/

* Taking notes on research.
Keep a folder of images. Keep subjects on what techniques or color or theme.
Study images. take them in photoshop an analize the color. 
Create a play list of studio visits and documentaries.
Journal about artists. 3 minute timer can be helpful. 
Put art in a spreadsheet.
** Organizing the rabbit hole.
Ellie reccomends Notion. of course they do lol.
Find a system that works for your brian, whatever it is.
* Ellie's Prsonal Process.
Organic through seeing shows and seeing galliers.
Would go every show they could in nyc for two years.
Lots of journaling and reflecting. 
Take a couple seconds to identify what they are connecting over with an art work.
Prompt: write 5 artists that linger in your brain, with 5 points about how their work and yours connect.
** Some art books Ellie reccomends when someone asked.
The book "20th centuray women" ab ex girl boss.
"Latin american women" cataloge of essays.
"We want it all" Poetry cataloge. Big fan of trans poetry in general.
Anything by Olivia Laing.

