* Jose.
The soundscape you made is very vivid, with many clear sounds. During the project I was immersed in the enviornment of the city streets that where familiar to me. The way you break the time into seperate spaces- crossing the street, walking by a store with music, going inside at the end- was enaging, and quite clever. My only technical critque is that sometimes I could hear the cuts you made in the audio, ie there were parts where I could see the metaphorical duct tape. Overall I think you made a really interesting project.
* Henna.
I found your desicion to play your project loudly over the room speakers, rather than over he head phones very engaging. The build of voices over time is also very effective, and the resolution was also well done. Creativly, I think you could have pushed the climax further somehow, perhaps with a digital noise, or tenitus buzz. All smmed, I think you succeeded in creating what you envisioned. 

* Victoria.
I didn't really get the idea of new york until you said it after. However I did this sence of transit and of the personal experience of it. It reminds me of montage sequence from travel vlogs. A lot of the sounds were very intimate, and I liked the rhythmic pattern of the work. 
