* What is preformance.
Seperate from acting, theater, etc.
Contextual to the enviornment. Iterated, not duplicated.
Exists in the interactions between the preformer and the audience.
Engages directly with social reality.
Messages of the medium include the form of the body, social functions, reality, and politics.
* Origins of preformance.
First in the 1910s with the Dada's happenings, but didn't take off until the 70s.
About breaking away from the traditional art disciplines.
Often concptual art.
* Art.
** Alex Da Corte.
*** ROY G BIV.
Instalation that brings togeater preformance art by Marcel Duchamp and their women alter ego Rose Selavy.

** Coco Fusco.
*** The Couple in the Cage.
Fusco and their partner dressed in American Indian style costume, stood in a cage, and with a plaque and announcer said they were the last remaining members of their tribe as though the were in a zoo. The cage was sat outside of museums.
*** Your Eyes will be an Empty World.
** Fabiano Kueve.
*** Alexander von Humbodlt.
Hombodlt was an explorer/colonizer. Kueve, a black man of mixed decent, reenacted Hoboldt's expedition.
** Tehching Hseih.
*** All Art Comes From Life.
Hseih is a preformance artist, the one that did that piece about the time clock and the photo every day for ages and made a time lapse.
** Mierle Laderman Ukeles.
Does maintenance art.
When they had a child, they childcare prevented them from doing art.
Examples of maintenance art include: washing the steps of a museum.
During a fiscal crisis in new york, they helped the sanitation department apply for a grant in performance art.
