* Introduction.
** Specific Generalization.
** Introduce Authors.
In "Immune To Reality" Daniel Gilbert examines mood, and the role the "psychological immune system" plays in one's mood.
Barbara Fredrickson's "Love 2.0" explores love from a scientific perspective.
** Thesis.
Defining happiness with skepticism ensures that one's understanding of happiness is sound and attainable.
* Body.
** Topic.
Without skepticism, false things will be include in one's understanding of happiness.
** Quote.
Gilbert writes "Clever Hans was no genius, but Osten was no fraud. Indeed he'd spent years patiently talking to his horse about mathematics and world affairs, and he was genuinely shocked and dismayed to learn that he had been fooling himself" (Gilbert 143).
** Anal.
Osten used intuition to describe the scenario. This lead Osten to conclude that the horse was learning math, and that teaching Hans math brought Osten happiness.
However, when rigorous doubt, that is skepticism, was applied, the truth was revealed, and made Osten very upset.
It is typical to define happiness with ones intuition. However it is also typical to find oneself operating under false expectations.
It is by supplanting intuition with doubt that the false aspects of one's understanding can be corrected.
In attaining the desirable mood, that is happiness, one must be critical of what is included in one definition.
** Quote.
For example, it is common for a romantic relationship, or a bond, to be a core aspect of one's expectations of happiness.
About bonds, Fredrickson writes "At times it feels great, while other times it hurts like hell. At times it lifts you up with grand dreams for your future and at other times oppresses you with shame about your inadequacies."
** Anal.
That is to say that bonds are not a sure way to attain desireable feelings. They are complex and come with many highs and lows.
When one assumes that a bond will lead to happiness, they have included a half-truth in their definition of happiness.
Just as Hans was not clever in the way Osten assumed that Hans was, a bond will not inspire the same emotions as is assumed.
** Conclude.
* Body.
** Topic.
Through skepticism, true things can be included in one's understanding of happiness.
** Quote.
Gilbert writes "people expect to feel equally bad when a tragic accident is the result of humon negligence as when it is the result of dumb luck but they actually feel worse when it is dumb luck and no one is blame worthy" (Gilvert 148).
** Anal.
That is to say that people place an unfounded confidence in they're ability to predict how they will feel.
Once again, intuition is a poor predictor, however in doubting it a consistant pattern emergese: that blaming someone makes a tragity makes the resulting mood less unpleasent.
This pattern is representive of a scientific fact, and can be considered truth.
By including this mechanic of the psyche in an understanding of what happiness is, that understanding becomes sound, and the emotion becomes more reliably attainable.
** Quote.
Fredrickson states that "people with hgher vagal tone, science has shown, are more flexible across a whole host of domains- physical, mental, and social."
** Anal.
Vagal tone, unlike intuition, has been proven to improve many areas of life related to mood.
Unlike romantic bonds, or teaching horses for that matter, vagal tone is a sound path towards better mood, specifically happiness.

** Conclude.
When doubted, vegal tone and the mechanics of blame both pass the test.
* Body.
** Topic.
The use value of a true understanding of happiness, is that with it one's emotional context is maliable, and happiness becomes attainable.
** Quote.
Gilber writes "that we are more likely to look for and find a poitive view of the things we're stuck with than the things that we're not" (Gilbert 150).
** Anal.
That is to say that when one is committed to something, volentarially or otherwise, the brain is naturally inclined to develope a positive relationship with it.
Therefore, one can cause a positive outcome by inducing this kind of stuckness.
As a knife is made sharp by filing off exess metal, an understanding of happiness that has been made true through skepticism is practical for ensuring attainment of happiness.
** Quote.
Fredrickson writes "Through eye contact and close attention to all manner of smiles- and the embodied simulations such visual intake triggers- your gut instincts about whom to trust and whom not to trust become more reliable. Rather than avoid all new people out of fear and suspicion, oxytocin helps you pick out on cuews that signal anpther person's goodwill and guides you to approach them with your own" (Fredrickson 128).
** Anal.
Scientific exploration has revealed this mechanic of oxytocin, in which it stimulates social bonding.
Therefore, oxytocin can be intentionally invoked in situatios where it would be most adventagous, such as when meeting new people, or trying to build new connections.
** Conclude.
The porpous of defining happiness is ultimently this, its attainment.
By defining skepticly, it becomes the most effective for attainment.
* Conclusion.
