* Introduction.
** Generalize specifically.
To be real is to have a concrete and independent existence, one that can be depended upon. However, how real something is a subjective interpretation. Thusly realness is less a factor of the plane of matter, and more of the mental plane. However that mental plane is subject to study, and like a lens, the way it effects vision can be understood.
** Introduce authors.
In "When I Woke Up Tuesday Morning It Was Friday" Martha Stout discusses trauma, and disassociation, through the accounts of Stout's clinical patience.
Daniel Gilbert's "Immune to Reality" analyzes how the human psyche responds to threats to it's mood, and the ways in which it responds.
In "Myth of The Ant Queen" Steven Johnson traces the invisible lines of emergent behavior from complex systems.
** State thesis.
Because reality is the aggregate of what appears real, factors that effect the perception of realness shape how one understands reality more than the objects of reality themselves.
* Body.
** Topic sentence.
Although the ego appears to be in charge of ones psyche, this leadership is illusory. In fact, social groups do more to influence how one acts, and understands reality.
** Quote and paraphrase.
"The driving was automatically carried out by some part of the mind, while the self part of the mind was worrying, daydreaming or listening to the radio. The experience is that of arriving at home without remembering the process of the trip" (Stout 426).
That is to say that preforming complex tasks does not require a much attention; tasks such as driving can be preformed automatically.
** Analyze.
Driving has the apperance of a centralilzed conductor. This center is often idenfitifed as the self. However when driving, the rules and customs of the road, that is the conventions of the social group of drivers, shape the decisions that the driver makes.
The driver still has an individual will, to get from origin to destination, but during their drive they melt into the larger society of drivers.
The driver's understanding of reality is reduced. They go from being present and engaged in the moment, to letting it pass by unprocessed.
** Close Read.
Driving is an automatic state. That is a state of consciousness in which presence and ego are reduced. During this state, the brain is still a complex and capable decision maker, however they are not engaged in understanding reality beyond the surface level required by the immediate circumstance.
The effect of this state is that drives are not focused the material plane of realit, rather they understand reality only as it includes the generalized functions of driving. This understanding still includes the idea of a center, with which the driver identifies, however the concreatness of that center is ambigious.
** Quote and paraphrase.
"We know now that systems like ant colonies don't have real leaders, that the very idea of an ant 'queen' is misleading. But the desire to find pacemakers in such systems has always been powerful" (Gilbert 190).
In other words, although there is an appearance of a central leader or pacemaker, such as an ant queen, such are only a label for an invisible figurehead, which does not in reality exist.
** Close Read.
A pacemaker is a device that is surgically implanted to help the heart keep rhythm. It sends out regular electric pulses, which the rest of the heart responds to. Used metaphorically, a pacemaker is that kind of conductor which keeps the system in line through dictation.
** Analyze.
Social groups present a particular narrative of reality. Such narratives usually include order, direction, and a central figure. Often it can seem as though someone in charge, when in reality there is only ever a collection of individuals. Still though, this narrative is impressed upon the individuals. They are then subconsciously asked to include this narrative in their understanding of reality. Generally, this narrative is automatically accepted.
In driving, each driver is an ant colony, in which an invisible queen appears to make choices. The driver understand their reality through being this queen, even though that like an ant queen, they have little actual leadership role.
** Conclusion.
There is a conflict between reality, and aones understanding of it in automatic states. That conflict is mediated by the social context, groups, and conventions one finds themselves in.
* Body.
** Topic sentence.
On the opposite hand, trauma altars the way the brain functions, putting one into a mode where one is less critical, and overall less present with, reality.
The extent of this is that one's understanding of reality is dependent more on invisible factors, such as social groups and trauma, than it is upon material factors.
** Quote and paraphrase.
"In a heartbeat, the present is perceptually and emotionally the past. These fragments of sensations and emotion are the amygdala-mediated memories of an afternoon three decades before." (Stout 416).
In this illustration, the biomechanics of trauma, particularly those of the amygdala, altar the perception of reality. The experience is literally composed of decade old memories.
** Analyze.
The truth of material existence is removed from the sensations produced by the brain. Only though the different senses is anyone aware of anything that exists.
However these senses are produced by biological components which do not perfectly express information.
Perceptions are what the brain processes as inputs. Despite this appearance, perceptions can be internal, emotional, hallucinatory, or otherwise removed from reality.
In the case of trauma, the brain has acquired a tendency to remember elements of the traumatic incident rather. When triggered in this way, one understands reality through the lens of the incident.
** Quote and paraphrase.
"It's easy to blame failure on the eccentricities of a unanimous judge, but it's much more difficult to blame failure on the eccentricities of a unanimous jury." (Gilbert 146)
In the event of a failure, placing the burden of that failure is easy when one's social group is only one other person, but when one is in a large group, doing so becomes hard, even impossible.
** Analyze.
Blame is a kind of causality, specifically it is the quality of being the source of an undesirable outcome. It exists only as an understanding; without an intelligence to connect events, the physics of the universe simply happens without thought. Whatever influences blame can then influence how one understands reality, even if that influence does not actually effect the events.
When there is a failure, it is in reality. But the blame for that failure is in one's mind, or more accurately in the part of the mind which formulates an understanding of reality. Depending on one's social context, that understanding part of the mind responds differently. Specifically, when there is a single scape goat, it is easy to understand the reality of oneself as blameless and innocent. However the opposite is also true.
** Close Read.
Blame is a kind of causality, specifically it is the quality of being the source of an undesirable outcome. It exists only as an understanding; without an intelligence to connect events, the physics of the universe simply happens without thought. Whatever influences blame can then influence how one understands reality, even if that influence does not actually effect the events.
** Conclusion.
When someone is embarrassed in front of a group, they are unable to hold the group as the cause for it, and will likely blame themselves.
When someone's trauma is triggered, they become unable to establish the causality of the physically present moment.
In both of theses ways, invisible factors alter the way one establishes and understands causality.
* Body.
** Topic sentence.
Social groups inform what is and is not considered credible. The range of possible understandings of reality that are limited to those that align with the group's belief.
** Quote and paraphrase.
"Because these volunteers suffered greatly, the intensity of their suffering triggered their defensive systems, which immediately began working to help them achieve a credible positive view of their experience." (Gilbert 148)
That is to say that when one pushes themselves into more painful experiences, they justify the pain they go through.
** Analyze.
The body is naturally adverse to painful experiences. When one is part of a group, however, that sociological environment changes ones response to justify the experience. Despite the real physical elements to the contrary, one comes to understand the pain as an acceptable part of reality. Whether or not the pain was worthwhile is weighed against the reputation of the group. And because the group is prestigious, the pain must have been worthwhile.
There is a link between suffering, that is being forced into an experience with negative valence or desirability, and the development of a credible positive valence of the whole experience. Credible here means not true or reliable, but believable or rather harmonious with what one already believes.
** Quote and paraphrase.
"Julia had come to assume, as abused children do, that she must be a horrible person who deserved these punishments" (Stout 420).
In other words, Julia manufactured a way to understand reality that was in harmony with Julia was already believing and experiencing.
** Analyze.
Julia was a member of an abusive family. That social group imbued a very powerful mindset into Julia. The social reality, that the family was permanent and just was the scale against which the pain was weighed. The pain was made out to be acceptable because the group was acceptable. Of course this is only half the story. In Julia's case, the experiences were so powerful as to cause trauma, and altar the memory and processing of the experience. This compounds the effect produced by the group. That is that the narrative which presents the valance of the group becomes the preferred understanding with which to view reality.
Julia's assumption was informed as much by their sociological environment as by internal factors. However the product of assumption is belief, that perception closely held as fact, despite its dubious relation to actual truth.
** Conclusion.
Both of these cases demonstrate how social groups inform what is and isn't credible, that is what is reasonable to assume. This limits the range of beliefs to those that contain a favorable view of the group, and enforce an understanding of reality were this belief is true.
* Conclusion.
Reality is subject to what is understood to be real. That understanding is subject to manipulation, specifically by trauma and by social groups.
Social groups invisibly manipulate how it is appropriate to act. There by, the reality one comes to understand is limited to those that contain the assumptions of the group.
Trauma can be triggered by mundane events, but it quickly supplants the present with elements of the present with that of the traumatizing incident.
In either case, the aggregate of real things is understood more through the trauma and social groups than by the what might be considered objective.
