* Introduction.
** Generalize specifically.
To be real is to have a concrete and independent existence, one that can be depended upon. However, how real something is a subjective interpretation. Thusly realness is less a factor of the plane of matter, and more of the mental plane. However that mental plane is subject to study, and like a lens, the way it effects vision can be understood.
** Introduce authors.
In "When I Woke Up Tuesday Morning It Was Friday" Martha Stout discusses trauma, and disassociation, through the accounts of Stout's clinical patience.
Daniel Gilbert's "Immune to Reality" analyzes how the human psyche responds to threats to it's mood, and the ways in which it responds.
In "Myth of The Ant Queen" Steven Johnson traces the invisible lines of emergent behavior from complex systems.
** State thesis.
Because reality is the aggregate of what appears real, factors that effect the perception of realness shape how one understands reality more than the objects of reality themselves.
* Body.
** Topic sentence.
Although the ego appears to be in charge of ones psyche, this leadership is illusory. In fact, social groups do more to influence how one acts, and understands reality.
** Quote and paraphrase.
"The driving was automatically carried out by some part of the mind, while the self part of the mind was worrying, daydreaming or listening to the radio. The experience is that of arriving at home without remembering the process of the trip" (Stout 426).
That is to say that preforming complex tasks does not require a much attention; tasks such as driving can be preformed automatically.
** Analyze.
Common sense would say that one needs to be present for driving, however this is simply not the case.
When driving, there are particular rules and customs a driver conforms to.
The driver has an individual will, to get from origin to destination, but during their drive, they melt into the larger society of drivers.
The driver's understanding of reality is reduced. They go from being present and engaged in the moment, to letting it pass by unprocessed.
Driving is an automatic state. That is a state of consciousness in which presence and ego are reduced. During this state, the brain is still a complex and capable decision maker, however they are not engaged in understanding reality beyond the surface level required by the immediate circumstance.
In this automatic state, drives are not focused the material plane of reality. Rather the understanding of their reality only includes the generalized functions of driving.
** Quote and paraphrase.
"We know now that systems like ant colonies don't have real leaders, that the very idea of an ant 'queen' is misleading. But the desire to find pacemakers in such systems has always been powerful" (Gilbert 190).
Paraphrase:
In other words, although there is an appearance of a central leader or pacemaker, such as an ant queen, such are only a label for an invisible figurehead, which does not in reality exist.
Explain:
Social groups present a particular narrative of reality. Such narratives usually include order, direction, and a central figure. Often it can seem as though someone in charge, when in reality there is only ever a collection of individuals. Still though, this narrative is impressed upon the individuals. They are then subconsciously asked to include this narrative in their understanding of reality. Generally, this narrative is automatically accepted.
Close Read:
A pacemaker is a device that is surgically implanted to help the heart keep rhythm. It sends out regular electric pulses, which the rest of the heart responds to. Used metaphorically, a pacemaker is that kind of conductor which keeps the system in line through dictation.
** Close Read.
** Analyze.
** Close Read.
** Conclusion.
* Body.
** Topic sentence.
** Quote and paraphrase.
** Analyze.
** Quote and paraphrase.
** Close Read.
** Analyze.
** Close Read.
** Conclusion.
* Body.
** Topic sentence.
** Quote and paraphrase.
** Analyze.
** Quote and paraphrase.
** Close Read.
** Analyze.
** Close Read.
** Conclusion.
* Conclusion.
